### ISSUE TITLE
Tensor flow sparse op

### ISSUE THREAD

**Issue by axdahl** [rwolst/sparse-cholesky-project#1]
Hi there, I'm wondering if you're still maintaining this repo or working on the tf op for sparse Cholesky?

Cheers!

**Comment by rwolst** [comment]
I am not really maintaining this repo or working on the TF op for sparse Cholesky as I found a workaround for my particular application (although it still would be nice to have in TF). To get the basic operation in TF is not too hard (requires reading through the documentation on op writing) as its simply a porting of for example the Eigen function. I'm not sure how to write the derivative op however.

**Comment by axdahl** [comment]
Cheers for the response.
